import { betterAuth } from "better-auth";
import { drizzleAdapter } from "better-auth/adapters/drizzle";
import { nextCookies } from "better-auth/next-js";

import { env } from "@/config/env";
import { db } from "@/lib/db";
import {
  accounts,
  sessions,
  users,
  verifications,
} from "@/lib/db/schema";
import { sendEmail } from "@/lib/email";
import { ResetPassword } from "@/lib/email/templates/reset-password";
import { VerifyEmail } from "@/lib/email/templates/verify-email";

/**
 * Better Auth server instance.
 *
 * - Uses our existing Drizzle `users` table (mapped as Better Auth's `user`
 *   model) plus three Better Auth-owned tables. We do NOT let Better Auth
 *   create its own user table.
 * - IDs are uuids generated by Postgres (`defaultRandom()`), so
 *   `advanced.database.generateId` is disabled.
 * - Better Auth's `image` field maps to our `avatarUrl` column; `role` and
 *   `bio` are exposed as read-only additional fields.
 */
export const auth = betterAuth({
  baseURL: env.BETTER_AUTH_URL,
  secret: env.BETTER_AUTH_SECRET,

  database: drizzleAdapter(db, {
    provider: "pg",
    schema: {
      user: users,
      session: sessions,
      account: accounts,
      verification: verifications,
    },
  }),

  advanced: {
    // Postgres generates the uuid primary keys via `defaultRandom()`.
    database: { generateId: false },
  },

  emailAndPassword: {
    enabled: true,
    minPasswordLength: 10,
    requireEmailVerification: true,
    sendResetPassword: async ({ user, url }) => {
      await sendEmail({
        to: user.email,
        subject: "Reset your HikeIt password",
        template: ResetPassword({ name: user.name, resetUrl: url }),
      });
    },
  },

  emailVerification: {
    sendOnSignUp: true,
    autoSignInAfterVerification: true,
    sendVerificationEmail: async ({ user, token }) => {
      // Point at our own page (which calls `verifyEmail` client-side and shows
      // loading/success/error states) rather than Better Auth's API endpoint.
      const verificationUrl = `${env.NEXT_PUBLIC_APP_URL}/verify-email?token=${token}`;
      await sendEmail({
        to: user.email,
        subject: "Verify your email · HikeIt",
        template: VerifyEmail({ name: user.name, verificationUrl }),
      });
    },
  },

  session: {
    // 7-day sessions, refreshed once a day of activity.
    expiresIn: 60 * 60 * 24 * 7,
    updateAge: 60 * 60 * 24,
  },

  user: {
    fields: {
      // Better Auth's `image` field lives in our `avatar_url` column.
      image: "avatarUrl",
    },
    additionalFields: {
      role: {
        type: "string",
        required: false,
        input: false,
        defaultValue: "hiker",
      },
      bio: {
        type: "string",
        required: false,
        input: false,
      },
    },
  },

  // `nextCookies` must be last: it lets server actions set auth cookies.
  plugins: [nextCookies()],
});

export type Session = typeof auth.$Infer.Session.session;
export type User = typeof auth.$Infer.Session.user;
