import { betterAuth } from "better-auth";
import { drizzleAdapter } from "better-auth/adapters/drizzle";
import { nextCookies } from "better-auth/next-js";

import { env } from "@/config/env";
import { db } from "@/lib/db";
import {
  accounts,
  rateLimits,
  sessions,
  users,
  verifications,
} from "@/lib/db/schema";
import { sendEmail } from "@/lib/email";
import { ResetPassword } from "@/lib/email/templates/reset-password";
import { VerifyEmail } from "@/lib/email/templates/verify-email";

/**
 * Better Auth server instance.
 *
 * - Uses our existing Drizzle `users` table (mapped as Better Auth's `user`
 *   model) plus three Better Auth-owned tables. We do NOT let Better Auth
 *   create its own user table.
 * - IDs are uuids generated by Postgres (`defaultRandom()`), so
 *   `advanced.database.generateId` is disabled.
 * - Better Auth's `image` field maps to our `avatarUrl` column; `role` and
 *   `bio` are exposed as read-only additional fields.
 */
export const auth = betterAuth({
  baseURL: env.BETTER_AUTH_URL,
  secret: env.BETTER_AUTH_SECRET,

  database: drizzleAdapter(db, {
    provider: "pg",
    schema: {
      user: users,
      session: sessions,
      account: accounts,
      verification: verifications,
      rateLimit: rateLimits,
    },
  }),

  /**
   * Rate limiting on every `/api/auth/*` endpoint, backed by the database so
   * the counter is shared across Vercel's serverless instances (the default
   * in-memory store gives each instance its own map, which is bypassable).
   * Credential endpoints get tighter custom rules than the global default.
   */
  rateLimit: {
    enabled: true,
    storage: "database",
    modelName: "rateLimit",
    // Baseline for every /api/auth/* endpoint: 10 attempts / 15 min per IP.
    window: 15 * 60,
    max: 10,
    customRules: {
      // Credential and email-dispatch endpoints are the brute-force and abuse
      // targets, so they stay tighter than the baseline.
      "/sign-in/email": { window: 15 * 60, max: 10 },
      "/sign-up/email": { window: 60 * 60, max: 5 },
      "/forget-password": { window: 60 * 60, max: 5 },
      "/reset-password": { window: 60 * 60, max: 5 },
      "/send-verification-email": { window: 60 * 60, max: 5 },
    },
  },

  advanced: {
    // Postgres generates the uuid primary keys via `defaultRandom()`.
    database: { generateId: false },
  },

  emailAndPassword: {
    enabled: true,
    minPasswordLength: 10,
    requireEmailVerification: true,
    sendResetPassword: async ({ user, url }) => {
      await sendEmail({
        to: user.email,
        subject: "Reset your HikeIt password",
        template: ResetPassword({ name: user.name, resetUrl: url }),
      });
    },
  },

  emailVerification: {
    sendOnSignUp: true,
    // Also re-send on a (correct-password) sign-in attempt by an unverified
    // user. Without this, anyone whose signup email failed to send — a bad
    // Resend key, a bounce, a spam folder — is stuck forever: sign-in returns
    // EMAIL_NOT_VERIFIED and there's no way to ask for another link. The send
    // happens only after the password is verified, so it can't be used to mail
    // arbitrary addresses.
    sendOnSignIn: true,
    autoSignInAfterVerification: true,
    sendVerificationEmail: async ({ user, token }) => {
      // Point at our own page (which calls `verifyEmail` client-side and shows
      // loading/success/error states) rather than Better Auth's API endpoint.
      const verificationUrl = `${env.NEXT_PUBLIC_APP_URL}/verify-email?token=${token}`;
      await sendEmail({
        to: user.email,
        subject: "Verify your email · HikeIt",
        template: VerifyEmail({ name: user.name, verificationUrl }),
      });
    },
  },

  session: {
    // 7-day sessions, refreshed once a day of activity.
    expiresIn: 60 * 60 * 24 * 7,
    updateAge: 60 * 60 * 24,
  },

  socialProviders: {
    google: {
      clientId: env.GOOGLE_CLIENT_ID,
      clientSecret: env.GOOGLE_CLIENT_SECRET,
    },
    // Optional until the Meta app exists — social sign-in just omits the
    // provider (no runtime error) when these aren't set yet.
    ...(env.FACEBOOK_CLIENT_ID && env.FACEBOOK_CLIENT_SECRET
      ? {
          facebook: {
            clientId: env.FACEBOOK_CLIENT_ID,
            clientSecret: env.FACEBOOK_CLIENT_SECRET,
          },
        }
      : {}),
  },

  user: {
    fields: {
      // Better Auth's `image` field lives in our `avatar_url` column.
      image: "avatarUrl",
    },
    additionalFields: {
      role: {
        type: "string",
        required: false,
        input: false,
        defaultValue: "hiker",
      },
      bio: {
        type: "string",
        required: false,
        input: false,
      },
    },
  },

  // Explicit, hardcoded origins — deliberately not a `*.vercel.app` (or even
  // a `*-fatlums-projects-686676d4.vercel.app`) wildcard. Better Auth matches
  // wildcards against the whole host with no path-segment boundary (see
  // `wildcardMatch` in better-auth/dist/utils/wildcard.mjs), and Vercel
  // project names are arbitrary, globally-unique strings anyone can register
  // for free — nothing stops an attacker who's seen one of our preview links
  // (the team slug is right there in the URL) from naming their own project
  // `evil-fatlums-projects-686676d4` and getting a real, valid
  // `evil-fatlums-projects-686676d4.vercel.app` that would pass that
  // wildcard. A trusted origin can receive verification-link and OAuth
  // callback redirects, so that's a real phishing/token-leak vector, not a
  // theoretical one. The new dev-branch workflow keeps this list short in
  // practice: only `dev`'s stable URL needs adding here, since that's the
  // one shared, standing test environment — individual `feat/*` preview
  // links aren't used for auth-flow testing and don't need an entry.
  trustedOrigins: [
    "https://hikeit.app",
    "https://www.hikeit.app",
    "https://hikeitapp.vercel.app",
    "https://hikeitapp-git-dev-fatlums-projects-686676d4.vercel.app",
    "http://localhost:3000",
  ],

  // `nextCookies` must be last: it lets server actions set auth cookies.
  plugins: [nextCookies()],
});

export type Session = typeof auth.$Infer.Session.session;
export type User = typeof auth.$Infer.Session.user;
