import type { NewTrail } from "../schema";

/**
 * 15 real Kosovo trails. Coordinates are approximate (good enough for the map).
 * All `verified: true` so they appear on the public listing. Re-running the
 * seed is safe — `run-seeds` inserts with `ON CONFLICT (slug) DO NOTHING`.
 */
export const trailSeeds: NewTrail[] = [
  {
    slug: "maja-e-gjeravices",
    name: "Maja e Gjeravicës",
    description:
      "Piku më i lartë i Kosovës (2,656m). Ngjitja kalon nëpër pyje të dendura dhe livadhe alpine.",
    region: "Bjeshkët e Namuna",
    city: "Pejë",
    countryCode: "XK",
    difficulty: "expert",
    distanceKm: "18.5",
    elevationGainM: 1456,
    estimatedDurationMin: 480,
    trailType: "out_and_back",
    startLat: "42.5123",
    startLng: "20.0891",
    seasons: ["summer", "autumn"],
    features: ["summit", "alpine_meadow", "forest"],
    verified: true,
  },
  {
    slug: "kanioni-i-rugovës",
    name: "Kanioni i Rugovës",
    description:
      "Një nga kanjionet më të bukura të Ballkanit. Rruga ndjek lumin Lumbardhi.",
    region: "Rugova",
    city: "Pejë",
    countryCode: "XK",
    difficulty: "easy",
    distanceKm: "12.0",
    elevationGainM: 320,
    estimatedDurationMin: 180,
    trailType: "out_and_back",
    startLat: "42.6234",
    startLng: "20.2156",
    seasons: ["spring", "summer", "autumn"],
    features: ["canyon", "river", "waterfall", "forest"],
    verified: true,
  },
  {
    slug: "sharri-brezovica",
    name: "Sharri — Brezovica",
    description:
      "Shtigje alpine në malin Sharr, afër qendrës turistike të Brezovicës.",
    region: "Sharr",
    city: "Ferizaj",
    countryCode: "XK",
    difficulty: "moderate",
    distanceKm: "14.0",
    elevationGainM: 780,
    estimatedDurationMin: 300,
    trailType: "loop",
    startLat: "42.1456",
    startLng: "21.0234",
    seasons: ["summer", "autumn"],
    features: ["summit", "alpine_meadow", "ski_resort"],
    verified: true,
  },
  {
    slug: "liqeni-i-badovcit",
    name: "Liqeni i Badovcit",
    description:
      "Shëtitje e lehtë rreth liqenit të Badovcit. Perfekte për familje.",
    region: "Prishtinë",
    city: "Prishtinë",
    countryCode: "XK",
    difficulty: "easy",
    distanceKm: "8.5",
    elevationGainM: 120,
    estimatedDurationMin: 120,
    trailType: "loop",
    startLat: "42.6789",
    startLng: "21.1567",
    seasons: ["spring", "summer", "autumn", "winter"],
    features: ["lake", "forest", "picnic"],
    verified: true,
  },
  {
    slug: "maja-e-koprishtit",
    name: "Maja e Koprishtit",
    description:
      "Ngjitje e mesme me pamje mahnitëse mbi Prizren dhe luginën.",
    region: "Sharr",
    city: "Prizren",
    countryCode: "XK",
    difficulty: "moderate",
    distanceKm: "10.0",
    elevationGainM: 650,
    estimatedDurationMin: 240,
    trailType: "out_and_back",
    startLat: "42.2134",
    startLng: "20.7456",
    seasons: ["spring", "summer", "autumn"],
    features: ["summit", "panorama", "historic"],
    verified: true,
  },
  {
    slug: "bjeshket-e-nemuna-loop",
    name: "Bjeshkët e Nemuna — Laku i Zi",
    description:
      "Unaza alpine nëpër Alpet Shqiptare. Laka e Zi është një gur druri natyror.",
    region: "Bjeshkët e Namuna",
    city: "Pejë",
    countryCode: "XK",
    difficulty: "hard",
    distanceKm: "22.0",
    elevationGainM: 1100,
    estimatedDurationMin: 420,
    trailType: "loop",
    startLat: "42.5678",
    startLng: "19.9876",
    seasons: ["summer", "autumn"],
    features: ["lake", "alpine_meadow", "summit", "forest"],
    verified: true,
  },
  {
    slug: "gadime-marble-cave",
    name: "Shpella e Gadimes",
    description:
      "Shtigje rreth shpellës mermeri të Gadimes, një ndër fenomenet natyrore të Kosovës.",
    region: "Lipjan",
    city: "Lipjan",
    countryCode: "XK",
    difficulty: "easy",
    distanceKm: "5.0",
    elevationGainM: 80,
    estimatedDurationMin: 90,
    trailType: "out_and_back",
    startLat: "42.5234",
    startLng: "21.1123",
    seasons: ["spring", "summer", "autumn", "winter"],
    features: ["cave", "historic", "family_friendly"],
    verified: true,
  },
  {
    slug: "mirusha-waterfalls",
    name: "Ujëvarat e Mirushës",
    description:
      "Seria e 13 ujëvarave dhe liqeneve të kaskadës së Mirushës. Spektakolare.",
    region: "Klinë",
    city: "Klinë",
    countryCode: "XK",
    difficulty: "easy",
    distanceKm: "7.0",
    elevationGainM: 150,
    estimatedDurationMin: 120,
    trailType: "out_and_back",
    startLat: "42.6123",
    startLng: "20.5678",
    seasons: ["spring", "summer", "autumn"],
    features: ["waterfall", "lake", "canyon", "swimming"],
    verified: true,
  },
  {
    slug: "kulla-e-drenicës",
    name: "Kulla e Drenicës — Shtigjet Historike",
    description:
      "Kombinim i historisë dhe natyrës nëpër luginën e Drenicës.",
    region: "Drenicë",
    city: "Skenderaj",
    countryCode: "XK",
    difficulty: "easy",
    distanceKm: "9.0",
    elevationGainM: 200,
    estimatedDurationMin: 150,
    trailType: "loop",
    startLat: "42.7456",
    startLng: "20.7890",
    seasons: ["spring", "summer", "autumn"],
    features: ["historic", "village", "panorama"],
    verified: true,
  },
  {
    slug: "maja-e-pashtrikut",
    name: "Maja e Pashtrikut",
    description:
      "Ngjitja drejt majës kufitare mes Kosovës dhe Shqipërisë. Pamje dyvendore.",
    region: "Gjakovë",
    city: "Gjakovë",
    countryCode: "XK",
    difficulty: "hard",
    distanceKm: "16.0",
    elevationGainM: 1050,
    estimatedDurationMin: 360,
    trailType: "out_and_back",
    startLat: "42.3456",
    startLng: "20.3456",
    seasons: ["summer", "autumn"],
    features: ["summit", "border", "panorama", "forest"],
    verified: true,
  },
  {
    slug: "prizren-kalaja",
    name: "Kalaja e Prizrenit — Shtigjet Alpine",
    description:
      "Nga qyteti historik i Prizrenit drejt malit pas kështjellës mesjetare.",
    region: "Sharr",
    city: "Prizren",
    countryCode: "XK",
    difficulty: "moderate",
    distanceKm: "11.0",
    elevationGainM: 550,
    estimatedDurationMin: 210,
    trailType: "out_and_back",
    startLat: "42.2123",
    startLng: "20.7345",
    seasons: ["spring", "summer", "autumn"],
    features: ["historic", "castle", "panorama", "city_view"],
    verified: true,
  },
  {
    slug: "liqeni-i-ibarrit",
    name: "Liqeni i Ibarrit — Ura e Vjetër",
    description:
      "Shëtitje e qetë nëpër bregun e liqenit. Pamje mbi malet e Kopaonikut.",
    region: "Mitrovicë",
    city: "Mitrovicë",
    countryCode: "XK",
    difficulty: "easy",
    distanceKm: "6.0",
    elevationGainM: 60,
    estimatedDurationMin: 90,
    trailType: "loop",
    startLat: "42.8901",
    startLng: "20.8678",
    seasons: ["spring", "summer", "autumn", "winter"],
    features: ["lake", "historic", "family_friendly"],
    verified: true,
  },
  {
    slug: "brod-restelica-loop",
    name: "Brod — Restelicë Alpine Loop",
    description:
      "Unazë alpine në Gorën e Kosovës. Fshatrat tradicionale dhe kullotat e larta.",
    region: "Sharr",
    city: "Dragash",
    countryCode: "XK",
    difficulty: "hard",
    distanceKm: "19.0",
    elevationGainM: 980,
    estimatedDurationMin: 390,
    trailType: "loop",
    startLat: "41.9876",
    startLng: "20.6543",
    seasons: ["summer", "autumn"],
    features: ["alpine_meadow", "village", "forest", "summit"],
    verified: true,
  },
  {
    slug: "decani-monastery-trail",
    name: "Manastiri i Deçanit — Shtigjet e Malit",
    description:
      "Nga manastiri mesjetar UNESCO drejt malit Deçan. Histori + natyrë.",
    region: "Bjeshkët e Namuna",
    city: "Deçan",
    countryCode: "XK",
    difficulty: "moderate",
    distanceKm: "13.0",
    elevationGainM: 700,
    estimatedDurationMin: 270,
    trailType: "out_and_back",
    startLat: "42.5432",
    startLng: "20.2987",
    seasons: ["spring", "summer", "autumn"],
    features: ["historic", "monastery", "forest", "river"],
    verified: true,
  },
  {
    slug: "germia-park-prishtina",
    name: "Parku i Gërmisë — Prishtinë",
    description:
      "Parka urbane e natyrës afër Prishtinës. Shtigje të shumëta, ideal për fillestarë.",
    region: "Prishtinë",
    city: "Prishtinë",
    countryCode: "XK",
    difficulty: "easy",
    distanceKm: "7.5",
    elevationGainM: 180,
    estimatedDurationMin: 120,
    trailType: "loop",
    startLat: "42.6654",
    startLng: "21.1987",
    seasons: ["spring", "summer", "autumn", "winter"],
    features: ["forest", "family_friendly", "picnic", "swimming"],
    verified: true,
  },
];
